from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping


@dataclass(frozen=True, slots=True)
class Settings:
    """Resolved filesystem settings for one console process."""

    project_root: Path
    data_dir: Path
    database_path: Path
    frontend_dist: Path
    gui_executor_enabled: bool = False
    adb_path: str | None = None
    adb_serial: str | None = None
    local_chat_endpoint: str | None = None
    local_chat_model: str | None = None
    local_chat_api_key: str | None = field(default=None, repr=False)
    cloud_chat_endpoint: str | None = None
    cloud_chat_model: str | None = None
    cloud_chat_api_key: str | None = field(default=None, repr=False)
    chat_request_timeout_seconds: float = 30.0
    chat_max_workers: int = 2
    chat_max_pending: int = 32
    soul_console_url: str = "http://127.0.0.1:5000"
    soul_request_timeout_seconds: float = 5.0
    soul_observation_timeout_seconds: float = 90.0
    # Generated by the local launcher for its per-process graceful-stop request.
    console_shutdown_token: str | None = field(default=None, repr=False)

    @classmethod
    def from_env(cls, env: Mapping[str, str] | None = None) -> "Settings":
        values = os.environ if env is None else env
        project_override = values.get("AI_GAME_PROJECT_ROOT", "").strip()
        if project_override:
            project_root = Path(project_override).expanduser().resolve()
        else:
            # .../apps/console/backend/ai_game_console/config.py -> project root
            project_root = Path(__file__).resolve().parents[4]

        data_override = values.get("AI_GAME_DATA_DIR", "").strip()
        data_dir = (
            Path(data_override).expanduser().resolve()
            if data_override
            else project_root / "runtime" / "console"
        )
        model_config = read_env_file(project_root / "config" / "model-runtime.env")
        cloud_config = read_env_file(project_root / "config" / "cloud-runtime.env")

        local_endpoint = _first_nonempty(
            values,
            "AI_GAME_LOCAL_CHAT_ENDPOINT",
            "AI_GAME_GUI_MODEL_ENDPOINT",
        )
        if local_endpoint is None:
            host = model_config.get("GUI_MODEL_HOST", "").strip()
            port = model_config.get("GUI_MODEL_PORT", "").strip()
            if host and port:
                local_endpoint = f"http://{host}:{port}/v1/chat/completions"

        cloud_endpoint = _first_nonempty(
            values,
            "AI_GAME_CLOUD_CHAT_ENDPOINT",
            "AI_GAME_CLOUD_PLANNER_ENDPOINT",
            "AI_GAME_CLOUD_ENDPOINT",
        ) or _first_nonempty(
            cloud_config,
            "CLOUD_CHAT_ENDPOINT",
            "CLOUD_PLANNER_ENDPOINT",
            "CLOUD_MODEL_ENDPOINT",
            "AI_GAME_CLOUD_CHAT_ENDPOINT",
            "AI_GAME_CLOUD_PLANNER_ENDPOINT",
        )
        cloud_model = _first_nonempty(
            values,
            "AI_GAME_CLOUD_CHAT_MODEL",
            "AI_GAME_CLOUD_PLANNER_MODEL",
            "AI_GAME_CLOUD_MODEL",
        ) or _first_nonempty(
            cloud_config,
            "CLOUD_CHAT_MODEL",
            "CLOUD_PLANNER_MODEL",
            "CLOUD_MODEL",
            "AI_GAME_CLOUD_CHAT_MODEL",
            "AI_GAME_CLOUD_PLANNER_MODEL",
        )

        return cls(
            project_root=project_root,
            data_dir=data_dir,
            database_path=data_dir / "console.db",
            frontend_dist=project_root / "apps" / "console" / "frontend" / "dist",
            gui_executor_enabled=(
                values.get("AI_GAME_GUI_EXECUTOR_ENABLED", "").strip() == "1"
            ),
            adb_path=values.get("AI_GAME_ADB_PATH", "").strip() or None,
            adb_serial=values.get("AI_GAME_ADB_SERIAL", "").strip() or None,
            local_chat_endpoint=local_endpoint,
            local_chat_model=(
                _first_nonempty(values, "AI_GAME_LOCAL_CHAT_MODEL")
                or model_config.get("GUI_MODEL_SERVED_NAME", "").strip()
                or None
            ),
            local_chat_api_key=(
                _first_nonempty(values, "AI_GAME_LOCAL_CHAT_API_KEY")
                or model_config.get("GUI_MODEL_API_KEY", "").strip()
                or None
            ),
            cloud_chat_endpoint=cloud_endpoint,
            cloud_chat_model=cloud_model,
            # Cloud credentials are intentionally read only from the process
            # environment, never from config/cloud-runtime.env.
            cloud_chat_api_key=_first_nonempty(
                values,
                "AI_GAME_CLOUD_CHAT_API_KEY",
                "AI_GAME_CLOUD_PLANNER_API_KEY",
                "AI_GAME_CLOUD_API_KEY",
            ),
            chat_request_timeout_seconds=_bounded_float(
                values.get("AI_GAME_CHAT_TIMEOUT_SECONDS"),
                default=30.0,
                minimum=1.0,
                maximum=120.0,
            ),
            chat_max_workers=_bounded_int(
                values.get("AI_GAME_CHAT_MAX_WORKERS"),
                default=2,
                minimum=1,
                maximum=8,
            ),
            chat_max_pending=_bounded_int(
                values.get("AI_GAME_CHAT_MAX_PENDING"),
                default=32,
                minimum=0,
                maximum=256,
            ),
            soul_console_url=(
                values.get("AI_GAME_SOUL_CONSOLE_URL", "").strip().rstrip("/")
                or "http://127.0.0.1:5000"
            ),
            soul_request_timeout_seconds=_bounded_float(
                values.get("AI_GAME_SOUL_TIMEOUT_SECONDS"),
                default=5.0,
                minimum=0.5,
                maximum=30.0,
            ),
            # Capturing an owner-held Android observation can legitimately
            # outlast the short control/inspect request budget.
            soul_observation_timeout_seconds=_bounded_float(
                values.get("AI_GAME_SOUL_OBSERVATION_TIMEOUT_SECONDS"),
                default=90.0,
                minimum=1.0,
                maximum=120.0,
            ),
            console_shutdown_token=(
                values.get("AI_GAME_CONSOLE_SHUTDOWN_TOKEN", "").strip() or None
            ),
        )


def read_env_file(path: Path) -> dict[str, str]:
    """Read non-secret shell-style key/value config without mutating ``os.environ``."""

    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line.removeprefix("export ").lstrip()
        key, separator, value = line.partition("=")
        if separator and key.strip():
            values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _first_nonempty(values: Mapping[str, str], *keys: str) -> str | None:
    for key in keys:
        value = values.get(key, "").strip()
        if value:
            return value
    return None


def _bounded_int(
    raw_value: str | None,
    *,
    default: int,
    minimum: int,
    maximum: int,
) -> int:
    try:
        parsed = int(raw_value) if raw_value is not None else default
    except ValueError:
        return default
    return parsed if minimum <= parsed <= maximum else default


def _bounded_float(
    raw_value: str | None,
    *,
    default: float,
    minimum: float,
    maximum: float,
) -> float:
    try:
        parsed = float(raw_value) if raw_value is not None else default
    except ValueError:
        return default
    return parsed if minimum <= parsed <= maximum else default
