from __future__ import annotations

import os
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, Mapping


RuntimeMode = Literal["legacy", "draining", "kernel_active"]


@dataclass(frozen=True, slots=True)
class Settings:
    """Resolved filesystem settings for one console process."""

    project_root: Path
    data_dir: Path
    database_path: Path
    frontend_dist: Path
    gui_executor_enabled: bool = False
    adb_path: str | None = None
    adb_serial: str | None = None
    local_chat_endpoint: str | None = None
    local_chat_model: str | None = None
    local_chat_api_key: str | None = field(default=None, repr=False)
    mobile_role_endpoint: str | None = None
    mobile_role_model: str | None = None
    mobile_role_api_key: str | None = field(default=None, repr=False)
    mobile_role_control_script: str | None = None
    cloud_chat_endpoint: str | None = None
    cloud_chat_model: str | None = None
    cloud_chat_api_key: str | None = field(default=None, repr=False)
    chat_request_timeout_seconds: float = 30.0
    chat_max_workers: int = 2
    chat_max_pending: int = 32
    # Generated by the local launcher for its per-process graceful-stop request.
    console_shutdown_token: str | None = field(default=None, repr=False)
    # Dedicated capability token for the narrow WeftMate/Harness execution API.
    # It is intentionally independent from Console and legacy device identities.
    harness_api_token: str | None = field(default=None, repr=False)
    # Runtime mode controls compatibility ownership. The normal launcher uses
    # the canonical Kernel path; legacy and draining remain rollback options.
    runtime_mode: RuntimeMode = "kernel_active"
    # Optional reversible Kernel probe used by compatibility diagnostics.
    kernel_canary_enabled: bool = False
    # Managed distribution instances are started by WeftMate through the
    # stdin-only contract.  They intentionally bring up the durable control
    # plane before an Android executor has been verified; the V2 adapter then
    # reports ``needs_setup`` instead of making an unsafe readiness claim.
    managed_runtime: bool = False
    # Deliberately opaque to the ordinary development configuration.  The
    # managed bootstrap installs a path guard that every current writable
    # composition root consults before opening a database, log, or artifact.
    managed_path_guard: Any | None = field(default=None, repr=False, compare=False)

    @classmethod
    def from_env(cls, env: Mapping[str, str] | None = None) -> "Settings":
        values = os.environ if env is None else env
        project_override = values.get("AI_GAME_PROJECT_ROOT", "").strip()
        if project_override:
            project_root = Path(project_override).expanduser().resolve()
        else:
            # .../apps/console/backend/ai_game_console/config.py -> project root
            project_root = Path(__file__).resolve().parents[4]

        data_override = values.get("AI_GAME_DATA_DIR", "").strip()
        data_dir = (
            Path(data_override).expanduser().resolve()
            if data_override
            else project_root / "runtime" / "console"
        )
        # The Console launcher owns the device-executor file.  These two
        # non-secret stage fence keys are read as current executor facts; the
        # process environment remains an explicit per-launch override.
        executor_runtime = read_env_file(project_root / "config" / "executor-runtime.env")
        model_config = read_env_file(project_root / "config" / "model-runtime.env")
        mobile_role_runtime = read_env_file(
            project_root / "config" / "mobile-role-runtime.env"
        )
        mobile_role_config_path = (
            values.get("AI_GAME_MOBILE_ROLE_CONFIG_PATH", "").strip()
            or mobile_role_runtime.get("AI_GAME_MOBILE_ROLE_CONFIG_PATH", "").strip()
        )
        mobile_role_config = read_openai_binding_json(mobile_role_config_path)
        cloud_config = read_env_file(project_root / "config" / "cloud-runtime.env")

        local_endpoint = _first_nonempty(
            values,
            "AI_GAME_LOCAL_CHAT_ENDPOINT",
            "AI_GAME_GUI_MODEL_ENDPOINT",
        )
        if local_endpoint is None:
            host = model_config.get("GUI_MODEL_HOST", "").strip()
            port = model_config.get("GUI_MODEL_PORT", "").strip()
            if host and port:
                local_endpoint = f"http://{host}:{port}/v1/chat/completions"

        cloud_endpoint = _first_nonempty(
            values,
            "AI_GAME_CLOUD_CHAT_ENDPOINT",
            "AI_GAME_CLOUD_PLANNER_ENDPOINT",
            "AI_GAME_CLOUD_ENDPOINT",
        ) or _first_nonempty(
            cloud_config,
            "CLOUD_CHAT_ENDPOINT",
            "CLOUD_PLANNER_ENDPOINT",
            "CLOUD_MODEL_ENDPOINT",
            "AI_GAME_CLOUD_CHAT_ENDPOINT",
            "AI_GAME_CLOUD_PLANNER_ENDPOINT",
        )
        cloud_model = _first_nonempty(
            values,
            "AI_GAME_CLOUD_CHAT_MODEL",
            "AI_GAME_CLOUD_PLANNER_MODEL",
            "AI_GAME_CLOUD_MODEL",
        ) or _first_nonempty(
            cloud_config,
            "CLOUD_CHAT_MODEL",
            "CLOUD_PLANNER_MODEL",
            "CLOUD_MODEL",
            "AI_GAME_CLOUD_CHAT_MODEL",
            "AI_GAME_CLOUD_PLANNER_MODEL",
        )

        return cls(
            project_root=project_root,
            data_dir=data_dir,
            database_path=data_dir / "console.db",
            frontend_dist=project_root / "apps" / "console" / "frontend" / "dist",
            gui_executor_enabled=(
                values.get("AI_GAME_GUI_EXECUTOR_ENABLED", "").strip() == "1"
            ),
            adb_path=values.get("AI_GAME_ADB_PATH", "").strip() or None,
            adb_serial=values.get("AI_GAME_ADB_SERIAL", "").strip() or None,
            local_chat_endpoint=local_endpoint,
            local_chat_model=(
                _first_nonempty(values, "AI_GAME_LOCAL_CHAT_MODEL")
                or model_config.get("GUI_MODEL_SERVED_NAME", "").strip()
                or None
            ),
            local_chat_api_key=(
                _first_nonempty(values, "AI_GAME_LOCAL_CHAT_API_KEY")
                or model_config.get("GUI_MODEL_API_KEY", "").strip()
                or None
            ),
            mobile_role_endpoint=(
                _first_nonempty(values, "AI_GAME_MOBILE_ROLE_ENDPOINT")
                or mobile_role_runtime.get("AI_GAME_MOBILE_ROLE_ENDPOINT", "").strip()
                or mobile_role_config.get("endpoint")
                or None
            ),
            mobile_role_model=(
                _first_nonempty(values, "AI_GAME_MOBILE_ROLE_MODEL")
                or mobile_role_runtime.get("AI_GAME_MOBILE_ROLE_MODEL", "").strip()
                or mobile_role_config.get("model")
                or None
            ),
            mobile_role_api_key=(
                _first_nonempty(values, "AI_GAME_MOBILE_ROLE_API_KEY")
                or mobile_role_runtime.get("AI_GAME_MOBILE_ROLE_API_KEY", "").strip()
                or mobile_role_config.get("api_key")
                or None
            ),
            mobile_role_control_script=(
                _first_nonempty(values, "AI_GAME_MOBILE_ROLE_CONTROL_SCRIPT")
                or mobile_role_runtime.get("AI_GAME_MOBILE_ROLE_CONTROL_SCRIPT", "").strip()
                or None
            ),
            cloud_chat_endpoint=cloud_endpoint,
            cloud_chat_model=cloud_model,
            # Cloud credentials are intentionally read only from the process
            # environment, never from config/cloud-runtime.env.
            cloud_chat_api_key=_first_nonempty(
                values,
                "AI_GAME_CLOUD_CHAT_API_KEY",
                "AI_GAME_CLOUD_PLANNER_API_KEY",
                "AI_GAME_CLOUD_API_KEY",
            ),
            chat_request_timeout_seconds=_bounded_float(
                values.get("AI_GAME_CHAT_TIMEOUT_SECONDS"),
                default=30.0,
                minimum=1.0,
                maximum=120.0,
            ),
            chat_max_workers=_bounded_int(
                values.get("AI_GAME_CHAT_MAX_WORKERS"),
                default=2,
                minimum=1,
                maximum=8,
            ),
            chat_max_pending=_bounded_int(
                values.get("AI_GAME_CHAT_MAX_PENDING"),
                default=32,
                minimum=0,
                maximum=256,
            ),
            console_shutdown_token=(
                values.get("AI_GAME_CONSOLE_SHUTDOWN_TOKEN", "").strip() or None
            ),
            harness_api_token=(
                values.get("AI_GAME_HARNESS_TOKEN", "").strip() or None
            ),
            runtime_mode=_parse_runtime_mode(
                values.get("AI_GAME_RUNTIME_MODE", "").strip()
            ),
            kernel_canary_enabled=(
                values.get("AI_GAME_KERNEL_CANARY_ENABLED", "").strip() == "1"
            ),
        )


def read_env_file(path: Path) -> dict[str, str]:
    """Read non-secret shell-style key/value config without mutating ``os.environ``."""

    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line.removeprefix("export ").lstrip()
        key, separator, value = line.partition("=")
        if separator and key.strip():
            values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def read_openai_binding_json(raw_path: str) -> dict[str, str]:
    """Read an explicitly selected local binding file without exposing secrets."""
    if not raw_path:
        return {}
    try:
        path = Path(raw_path).expanduser().resolve()
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError, json.JSONDecodeError):
        return {}
    if not isinstance(payload, dict):
        return {}
    host = str(payload.get("host") or "").strip()
    port = payload.get("port")
    model = str(payload.get("alias") or payload.get("model_name") or "").strip()
    keys = payload.get("api_keys")
    api_key = str(keys[0]).strip() if isinstance(keys, list) and keys else ""
    try:
        port_number = int(port)
    except (TypeError, ValueError):
        return {}
    if host not in {"127.0.0.1", "localhost", "::1"} or not 1 <= port_number <= 65535:
        return {}
    if not model:
        return {}
    return {
        "endpoint": f"http://{host}:{port_number}/v1/chat/completions",
        "model": model,
        "api_key": api_key,
    }


def _first_nonempty(values: Mapping[str, str], *keys: str) -> str | None:
    for key in keys:
        value = values.get(key, "").strip()
        if value:
            return value
    return None


def _bounded_int(
    raw_value: str | None,
    *,
    default: int,
    minimum: int,
    maximum: int,
) -> int:
    try:
        parsed = int(raw_value) if raw_value is not None else default
    except ValueError:
        return default
    return parsed if minimum <= parsed <= maximum else default


def _bounded_float(
    raw_value: str | None,
    *,
    default: float,
    minimum: float,
    maximum: float,
) -> float:
    try:
        parsed = float(raw_value) if raw_value is not None else default
    except ValueError:
        return default
    return parsed if minimum <= parsed <= maximum else default


def _parse_runtime_mode(raw_value: str) -> RuntimeMode:
    """Parse the explicit cutover mode, defaulting normal startup to Kernel.

    A non-empty unknown value is rejected instead of silently re-enabling
    Legacy writers after a misspelled deployment setting.
    """
    normalized = raw_value.lower().strip()
    if not normalized:
        return "kernel_active"
    if normalized == "legacy":
        return "legacy"
    if normalized in ("draining", "drain"):
        return "draining"
    if normalized in ("kernel_active", "kernel", "new"):
        return "kernel_active"
    raise ValueError(f"Unknown AI_GAME_RUNTIME_MODE: {raw_value}")
