[CmdletBinding()]
param(
    [ValidateSet(0)]
    [int]$VmIndex = 0
)

$ErrorActionPreference = 'Stop'

$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$ConfigPath = Join-Path $ProjectRoot 'config\executor-runtime.env'
$MuMuCliPath = 'D:\Software\MuMuPlayer\nx_main\mumu-cli.exe'
$MuMuAdbPath = 'D:\Software\MuMuPlayer\nx_device\15.0\shell\adb.exe'

function Assert-ExpectedExecutable {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $fullPath = [System.IO.Path]::GetFullPath($Path)
    if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
        throw "$Description is missing: $fullPath"
    }
    if (-not [System.IO.Path]::GetFileName($fullPath).Equals('adb.exe', [System.StringComparison]::OrdinalIgnoreCase) -and
        $Description -eq 'MuMu ADB') {
        throw "$Description must resolve to adb.exe: $fullPath"
    }
    return $fullPath
}

function Get-RequiredBoolean {
    param(
        [Parameter(Mandatory = $true)]$Info,
        [Parameter(Mandatory = $true)][string]$PropertyName
    )

    $value = $Info.$PropertyName
    if ($value -ne $true) {
        throw "MuMu VM $VmIndex is not started ($PropertyName is not true). The sync script will not start it."
    }
}

function Get-LoopbackAdbSerial {
    param([Parameter(Mandatory = $true)]$Info)

    Get-RequiredBoolean $Info 'is_android_started'
    Get-RequiredBoolean $Info 'is_process_started'
    if ([string]$Info.player_state -ne 'start_finished') {
        throw "MuMu VM $VmIndex is not ready (player_state=$($Info.player_state)). The sync script will not start it."
    }
    if ([string]$Info.adb_host_ip -ne '127.0.0.1') {
        throw "MuMu reported a non-loopback ADB host; refusing to configure it."
    }

    $port = 0
    if (-not [int]::TryParse([string]$Info.adb_port, [ref]$port) -or $port -lt 1 -or $port -gt 65535) {
        throw 'MuMu reported an invalid ADB port.'
    }
    return "127.0.0.1:$port"
}

function Write-ExecutorRuntimeConfigAtomically {
    param([Parameter(Mandatory = $true)][string]$Serial)

    $content = @(
        '# Generated by scripts/sync-mumu-executor.ps1 from the already-running MuMu VM 0.',
        '# This is non-secret local configuration. Re-run sync after MuMu changes its dynamic ADB port.',
        'AI_GAME_GUI_EXECUTOR_ENABLED=1',
        "AI_GAME_ADB_PATH=$MuMuAdbPath",
        "AI_GAME_ADB_SERIAL=$Serial",
        ''
    ) -join [Environment]::NewLine

    $configDirectory = Split-Path -Parent $ConfigPath
    New-Item -ItemType Directory -Force -Path $configDirectory | Out-Null
    $temporaryPath = Join-Path $configDirectory ".executor-runtime.env.$PID.$([guid]::NewGuid().ToString('N')).tmp"
    $backupPath = Join-Path $configDirectory ".executor-runtime.env.$PID.$([guid]::NewGuid().ToString('N')).bak"
    try {
        [System.IO.File]::WriteAllText($temporaryPath, $content, [System.Text.UTF8Encoding]::new($false))
        if ([System.IO.File]::Exists($ConfigPath)) {
            # File.Replace is atomic on the same volume and is available in
            # both Windows PowerShell 5.1 and PowerShell 7.  File.Move's
            # overwrite overload exists only on newer .NET runtimes.
            # .NET Framework requires a legal backup path even though modern
            # .NET accepts null here.  The backup is removed only after the
            # atomic replacement has succeeded.
            [System.IO.File]::Replace($temporaryPath, $ConfigPath, $backupPath)
        } else {
            [System.IO.File]::Move($temporaryPath, $ConfigPath)
        }
    } finally {
        Remove-Item -LiteralPath $temporaryPath -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $backupPath -Force -ErrorAction SilentlyContinue
    }
}

$resolvedCliPath = Assert-ExpectedExecutable $MuMuCliPath 'MuMu CLI'
$resolvedAdbPath = Assert-ExpectedExecutable $MuMuAdbPath 'MuMu ADB'

# `info` is the only MuMu CLI subcommand used here.  In particular, this
# script never invokes create, clone, delete, control, or any start operation.
$infoOutput = & $resolvedCliPath info --vmindex $VmIndex 2>&1 | Out-String
if ($LASTEXITCODE -ne 0) {
    throw "MuMu CLI info failed for VM ${VmIndex}: $infoOutput"
}
try {
    $info = $infoOutput | ConvertFrom-Json
} catch {
    throw "MuMu CLI returned invalid VM info for VM ${VmIndex}: $infoOutput"
}
if ($info -is [array]) {
    if ($info.Count -ne 1) { throw "MuMu CLI returned $($info.Count) VM records; expected exactly one for VM $VmIndex." }
    $info = $info[0]
}
if ([string]$info.index -ne $VmIndex.ToString()) {
    throw "MuMu CLI returned VM index '$($info.index)' instead of '$VmIndex'."
}

$serial = Get-LoopbackAdbSerial $info
$connectOutput = & $resolvedAdbPath connect $serial 2>&1 | Out-String
if ($LASTEXITCODE -ne 0) {
    throw "ADB connect failed for ${serial}: $connectOutput"
}
$deviceState = (& $resolvedAdbPath -s $serial get-state 2>&1 | Out-String).Trim()
if ($LASTEXITCODE -ne 0 -or $deviceState -ne 'device') {
    throw "ADB verification failed for ${serial}: expected device, got '$deviceState'."
}

Write-ExecutorRuntimeConfigAtomically $serial
[pscustomobject]@{
    VmIndex = $VmIndex
    Serial = $serial
    AdbPath = $resolvedAdbPath
    ConfigPath = $ConfigPath
    Status = 'verified_and_written'
} | Format-List
